//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienVienDongPhim
    {
        public int MaPhim { get; set; }
        public int MaDienVien { get; set; }
        public string TenVaiDien { get; set; }
    
        public virtual DienVien DienVien { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
