//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDangKy
    {
        public int MaPhieuDangKy { get; set; }
        public Nullable<int> MaGoiDV { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public Nullable<double> KhuyenMai { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual GoiDichVu GoiDichVu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
