//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.DanhGiaPhims = new HashSet<DanhGiaPhim>();
            this.DienVienDongPhims = new HashSet<DienVienDongPhim>();
            this.DaoDiens = new HashSet<DaoDien>();
            this.HashTags = new HashSet<HashTag>();
            this.TheLoais = new HashSet<TheLoai>();
        }
    
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public Nullable<System.DateTime> NgaySanXuat { get; set; }
        public string NoiDungPhim { get; set; }
        public string NoiDungPhimTomTat { get; set; }
        public Nullable<double> DiemIMDB { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string HinhBanner { get; set; }
        public string LinkPhim { get; set; }
        public string LinkPhimVip { get; set; }
        public string TrailerPhim { get; set; }
        public Nullable<int> MaNuoc { get; set; }
        public Nullable<int> MaNgonNgu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaPhim> DanhGiaPhims { get; set; }
        public virtual DatNuoc DatNuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DienVienDongPhim> DienVienDongPhims { get; set; }
        public virtual NgonNgu NgonNgu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaoDien> DaoDiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HashTag> HashTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
    }
}
